### ISSUE TITLE
Purge AMI ID with timestamp or commit sha

### ISSUE THREAD

**Issue by monyth** [bonclay7/aws-amicleaner#15]
Hello,

Do you think it's possible to delete AMI ID older than 10 days or with commit sha?

**Comment by bonclay7** [comment]
Hello !
Right now, it isn't possible to clean with `older than 10 days`, but it could be a nice feature...

But you can remove with a commit sha if it is a tag, you can try something like that :
```bash
amicleaner/cli.py --mapping-key commit_sha --mapping-value commit-value --keep-previous 0
```
I set `keep-previous` to __zero__ because I suppose you have only one AMI per commit

**Comment by monyth** [comment]
And you can delete with timestamp?
When you use keep-previous with 10 that's mean you keep 10 last versions of AMI?

**Comment by bonclay7** [comment]
No, there isn't a timestamp yet ...
And the `keep-previous` argument is indeed a way to preserve amis sorted on `creation-date` for those who share a same tag. 

For your use case, if your AMI has a `name` tag, you can give the `name` as a mapping-value and control the number of AMIs of that name you want to keep

**Comment by bonclay7** [comment]
No, there isn't a timestamp yet ...
And the `keep-previous` argument is indeed a way to preserve amis sorted on `creation-date` for those who share a same tag. 

For your use case, I think you can use the following syntax :
```bash
amicleaner/cli.py --mapping-key name --keep-previous 2
```
It will regroup all the AMIs which have the same name, reverse sort them on the `creation-date`, and remove until `keep-previous` argument which is __4__ by default

**Comment by monyth** [comment]
The method work but I have an issue with delete which generate an error and stop.
![image](https://cloud.githubusercontent.com/assets/15730319/14176655/68a44c70-f752-11e5-88c3-b34d4fc73ffd.png)

In parallel the delete for AMI in error is done after each minutes.

**Comment by bonclay7** [comment]
Do you have the last version of the repo ? This issue has already been fixed
I've just tested, and it works fine :smile: 
```bash
amicleaner/cli.py --mapping-key name --mapping-values test1 --full-report --keep-previous 10                                                                    
```

**Comment by monyth** [comment]
The last version of repo ? Where can I find info?

**Comment by bonclay7** [comment]
just a git clone of the project.
But I think I understand what's happening here. AMI deregistering is asynchronous, and it is scheduled by AWS. In my case, the deregistering operation was done instantly so I was able to remove the related snapshot. Interesting ...

**Comment by monyth** [comment]
Same after git clone with last version I have same issue.
1 AMI id is deleted but not other. I have an error message and after script stopped.
