### ISSUE TITLE
Do you have plans to release a new version on pypi?

### ISSUE THREAD

**Issue by theospears** [bonclay7/aws-amicleaner#41]
I would love to be able to deploy this, but am currently blocked on the issue fixed by https://github.com/bonclay7/aws-amicleaner/pull/40

**Comment by bonclay7** [comment]
I planed to add some more fix, but I haven't got time, so I'll submit directly the current status on pypi with https://github.com/bonclay7/aws-amicleaner/pull/42

**Comment by bonclay7** [comment]
Done :), I will close this issue

**Comment by theospears** [comment]
Thanks!
