### ISSUE TITLE
Interactively delete by group or filter by group

### ISSUE THREAD

**Issue by ervoiox** [bonclay7/aws-amicleaner#60]
Hi,

Is it possible to interactively delete groups instead of deleting them all at once or filter to a specific group value?

IE:

```
Retrieving AMIs to clean ...

AMIs to be removed:
+--------------------+------------+
|     Group name     | candidates |
+--------------------+------------+
|     abc1234567     |     2      |
| no-tags (excluded) |     1      |
|     example1ab     |     7      |
+--------------------+------------+
```

But I only want to clean up `example1ab`.

**Comment by bonclay7** [comment]
You can use these options (__keep-previous__ to 0 to delete them all) :

```bash
amicleaner --mapping-key name --mapping-values example1ab --keep-previous 0
```

**Comment by ervoiox** [comment]
Hi @bonclay7 to clarify, the Group names displayed are coming from tags (lets say `Group`), is there a way to filter to a specific tag value?

**Comment by bonclay7** [comment]
Hi !
Indeed, the group names are coming from tags.
There are two ways to filter:
- on one way, you give a tag name, let's say `Group`, and the tool will try and regroup all of its different values, and clean them (except those who don't have this tag).
- on the other hand, if you want to delete specific values of `Group`, you will have to specify using the example in my previous comment, assuming `example1ab` is one of the values of `Group`

I hope, I explained correctly 😆

**Comment by ervoiox** [comment]
@bonclay7 Thank you for the clarifying, the 2nd approach was exactly what I was looking for! The key `name` made me think it referred to the AMI name. :stuck_out_tongue:
