### ISSUE TITLE
Date checking

### ISSUE THREAD

**Issue by ameir** [bonclay7/aws-amicleaner#62]
This tool looks great, and is _almost_ exactly what we need.  One constraint we need to enforce is that we do not want to delete anything that's less than six months old.  

We have a central account that creates + shares AMIs with other accounts, and want to guarantee an AMI exists for at least that amount of time.

If this can be added, that would be awesome.

**Comment by bonclay7** [comment]
Thanks @ameir for this request. I will look into that.
Although this is not supported for now, maybe you can use the __keep-previous__ constraint

**Comment by pmg1991** [comment]
@bonclay7 @actionjack  Hi folks, I'm working on this. Will write proper test cases and and ad property for it  . I'll submit the pull request in a day or two.

**Comment by pmg1991** [comment]
Please check if https://github.com/bonclay7/aws-amicleaner/pull/83
full fills you needs.

**Comment by pmg1991** [comment]
Is pull request working fine? Anybody got a chance to test it?

**Comment by bonclay7** [comment]
Works fine for me, will release it soon
