### ISSUE TITLE
Region CLI Flag

### ISSUE THREAD

**Issue by sidewinder12s** [bonclay7/aws-amicleaner#63]
Allow the user to pass a region from the CLI instead of only relying on the credentials provider.

**Comment by dmytroleonenko** [comment]
You can always use AWS_DEFAULT_REGION (or [any other available boto variables](http://boto3.readthedocs.io/en/latest/guide/configuration.html))

**Comment by actionjack** [comment]
as @dmytroleonenko suggest I just do 

AWS_DEFAULT_REGION=us-east-1 amicleaner --mapping-key name --mapping-values frontend --full-report --ami-min-days 45 -f
