### ISSUE TITLE
--dry-run

### ISSUE THREAD

**Issue by spinus** [bonclay7/aws-amicleaner#77]
Hello,

Is there any way currently to see what will be deleted without actually deleting it?
Would like to see what will be wiped out, currently I don't see any option, but not sure if I missed that?

**Comment by tedivm** [comment]
It'll ask for confirmation before deleting anything.

If you pipe in 'n' to the command you'll get a complete dry run-

`yes 'n' | amicleaner`

**Comment by bonclay7** [comment]
Thanks @tedivm for the explanations !
